// AUTO-GENERATED by archival - do not edit.

/** An uploaded file. `url` is "" until something has been uploaded. */
export interface ArchivalFile {
  display_type: "image" | "video" | "audio" | "upload";
  filename: string;
  sha: string;
  mime: string;
  name?: string;
  description?: string;
  url: string;
}

/** A `meta` field: free-form TOML, converted to JSON. */
export type ArchivalMeta =
  | string
  | number
  | boolean
  | null
  | ArchivalMeta[]
  | { [key: string]: ArchivalMeta };

export interface InfoObject {
  /** `<object name>/<file name>` this object was read from. */
  path: string;
  /** The object's `order`, or null when it is unordered. */
  order: number | null;
  first_name: string | null;
  last_name: string | null;
  business_name: string | null;
  title: string | null;
  location: string | null;
  image: ArchivalFile | null;
  og_image: ArchivalFile | null;
  favicon: ArchivalFile | null;
  about: string | null;
  description: string | null;
  contact_header: string | null;
  contact_message: string | null;
  contact_complete_header: string | null;
  contact_complete_message: string | null;
}

export interface ServiceObject {
  /** `<object name>/<file name>` this object was read from. */
  path: string;
  /** The object's `order`, or null when it is unordered. */
  order: number | null;
  name: string | null;
  description: string | null;
  body: string | null;
  price: string | null;
}

export interface TestimonialObject {
  /** `<object name>/<file name>` this object was read from. */
  path: string;
  /** The object's `order`, or null when it is unordered. */
  order: number | null;
  quote: string | null;
  author: string | null;
  thumbnail: ArchivalFile | null;
}

export interface GoogleFormObject {
  /** `<object name>/<file name>` this object was read from. */
  path: string;
  /** The object's `order`, or null when it is unordered. */
  order: number | null;
  form_id: string | null;
  name_field_id: string | null;
  email_field_id: string | null;
  phone_field_id: string | null;
  service_field_id: string | null;
  comments_field_id: string | null;
}

export interface PrivacyPolicyObject {
  /** `<object name>/<file name>` this object was read from. */
  path: string;
  /** The object's `order`, or null when it is unordered. */
  order: number | null;
  content: string | null;
}

export interface TermsOfServiceObject {
  /** `<object name>/<file name>` this object was read from. */
  path: string;
  /** The object's `order`, or null when it is unordered. */
  order: number | null;
  content: string | null;
}

/** Every object in the site, keyed by name. */
export interface ArchivalObjects {
  info: InfoObject;
  service: ServiceObject[];
  testimonial: TestimonialObject[];
  google_form: GoogleFormObject;
  privacy_policy: PrivacyPolicyObject;
  terms_of_service: TermsOfServiceObject;
}

declare module "@archival/carrier" {
  interface SiteObjects extends ArchivalObjects {}
}
