#:schema https://archival.dev/schemas/archival_objects.schema.json
# This file is used to define the objects available on your site.

[publication]
name = "string"
tagline = "string"
og_image = "image"

[sections]
template = "section"
name = "string"
slug = "string"

[authors]
name = "string"
title = "string"
photo = "image"
bio = "string"

[stories]
template = "story"
headline = "string"
subheadline = "string"
slug = "string"
section = "string"
author = "string"
date = "string"
image = "image"
cover_url = "string"
image_caption = "string"
featured = "boolean"
body = "markdown"
