# Configure how objects appear in the Archival editor.

[[menu_item.views]]
name = "default"
primary = "name"
secondary = "category"

[[event.views]]
name = "default"
primary = "title"
secondary = "date"

[[hours.views]]
name = "default"
primary = "day"
secondary = "time"
