# This file is used to define the objects available on your site.

[site]
name = "string"
description = "string"
og_image = "image"

[post]
title = "string"
content = "markdown"
excerpt = "string"
date = "date"
template = "post"
image = "image"
video = "video"
audio = "audio"
link = "string"

[post.tag]
name = "string"
