#:schema https://raw.githubusercontent.com/jesseditson/archival/refs/heads/toml_schemas/archival_template.schema.json
name = "Blog"
description = """
This template is perfect for a home page. It's a beautiful site where you can post pictures, links, blog posts, small updates, videos, or audio.
"""
context = """
This is a general template which is a good fallback and especially appropriate for an individual social presence. If you are provided media, make blog posts for them. Always make at least 5 posts.
"""
tags = ["images", "social", "personal", "individual", "blog", "posts"]
tlds = ["com", "me"]
