[personal]
name = "string"
title = "string"
action_line = "string"
tagline = "string"
full_about = "markdown"
og_image = "image"

[experience]
title = "string"
description = "markdown"

[experience.job]
title = "string"
company = "string"
dates = "string"
description = "markdown"

[contact]
title = "string"
description = "markdown"
email = "string"

[resume]
file = "upload"

[work]
title = "string"
description = "markdown"

[work.project]
name = "string"
description = "markdown"
tags = "string"
image = "image"
