# This file is used to define the objects available on your site.

[site]
name = "string"
description = "string"

[post]
title = "string"
content = "markdown"
excerpt = "string"
date = "date"
tags = "string"
template = "post"
[[post.media]]
name = "image"
type = "image"
[[post.media]]
name = "video"
type = "video"
[[post.media]]
name = "audio"
type = "audio"
[[post.media]]
name = "link"
type = "string"
