name = "Pale Stations"
description = "Atmospheric indie rock and shimmering electronic textures."
merch_url = "https://yourbandname.bandcamp.com"

[image]
sha = "4e05635b75ae6e626518874ad0ebff3e4a5ce759a379e1722e50c89291674891"
filename = "band-bg-placeholder-01.jpg"
mime = "image/jpeg"
display_type = "image"
