title = "Where I've Worked"

description = """
A few of the places I've spent time building things and shipping work I'm proud of.
"""

[[job]]
title = "Lead UX Designer"
company = "DesignHub"
dates = "2021 — Present"
description = """
Led the UX team in revamping the company's flagship product, resulting in a 30% increase in user engagement. Conducted user research, created personas, and collaborated closely with cross-functional teams to implement design solutions that balanced user needs with technical feasibility.
"""

[[job]]
title = "Product Designer"
company = "Innovate Studios"
dates = "2018 — 2021"
description = """
Contributed to a variety of projects ranging from mobile applications to enterprise software. Designed an e-commerce platform that streamlined the shopping experience, leading to a 20% boost in conversion rates. Honed my ability to adapt to different industries and unique user requirements.
"""
