name = "Jesse Ditson"
title = "Product Designer"
action_line = "I create things."
tagline = "I'm a designer & software engineer specializing in building exceptional interactive products."
full_about = """
I’m a passionate UX designer with over seven years of experience crafting intuitive and engaging digital experiences. My journey began with a fascination for how technology can enrich people’s lives, leading me to pursue a degree in Human-Computer Interaction. I thrive on transforming complex problems into simple, user-friendly interfaces that delight users and meet business goals.

My approach is rooted in empathy and a deep understanding of user needs. I believe that the best designs emerge from collaborative processes, where diverse perspectives come together to solve challenging problems. When I’m not sketching wireframes or prototyping interactions, you’ll find me staying up-to-date with the latest design trends, attending workshops, or exploring new tools to enhance my skill set.
"""