name = "Rachel Stewart"
bio = """
Rachel is a culture journalist who brings a unique perspective to tech discussions. 
With a background in media studies, they focus on how technology shapes our social interactions.
"""
twitter = "https://twitter.com/rachelstewart"
linkedin = ""
instagram = "https://instagram.com/rachelstewart"

[avatar]
sha = "2c3e7e5dc7a50926d3ab98ccd9ccd601f9a83a6635c4f9a6cafb647ef30a7301"
filename = "professional-1-testimonial-avatar-1.jpg"
mime = "image/jpeg"
display_type = "image"
