order = 14
title = "Barbershop Simulator"
content = """
A classic mixtape from a game that never was.
"""
excerpt = "A classic mixtape from a game that never was."
date = 2024-11-14T00:00:00
tags = "nature, video"

[audio]
sha = "dc03cadf2ed61bf9003fdc5268f26051ec9b3603ae099167b59609d05fe56055"
filename = "barbershop-simulator.mp3"
mime = "audio/mpeg"
display_type = "audio"