order = 3
title = "On Simplicity"
content = """
> Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.
>
> — Antoine de Saint-Exupéry
"""
excerpt = "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away."
date = 2024-11-10T00:00:00

[[tag]]
name = "design"
[[tag]]
name = "thoughts"
