order = 9
title = "On Creative Work"
content = """
> The most important thing is the thing you make next. As soon as one work is done, you move on to the next. You don't pause to wait for approval.
>
> — Rick Rubin
"""
excerpt = "The most important thing is the thing you make next."
date = 2024-11-04T00:00:00

[[tag]]
name = "creativity"
[[tag]]
name = "thoughts"
