// AUTO-GENERATED by archival - do not edit.

/** An uploaded file. `url` is "" until something has been uploaded. */
export interface ArchivalFile {
  display_type: "image" | "video" | "audio" | "upload";
  filename: string;
  sha: string;
  mime: string;
  name?: string;
  description?: string;
  url: string;
}

/** A `meta` field: free-form TOML, converted to JSON. */
export type ArchivalMeta =
  | string
  | number
  | boolean
  | null
  | ArchivalMeta[]
  | { [key: string]: ArchivalMeta };

export interface SiteObject {
  /** `<object name>/<file name>` this object was read from. */
  path: string;
  /** The object's `order`, or null when it is unordered. */
  order: number | null;
  name: string | null;
  description: string | null;
  og_image: ArchivalFile | null;
  favicon: ArchivalFile | null;
}

export interface PostObject {
  /** `<object name>/<file name>` this object was read from. */
  path: string;
  /** The object's `order`, or null when it is unordered. */
  order: number | null;
  title: string | null;
  content: string | null;
  excerpt: string | null;
  date: string | null;
  image: ArchivalFile | null;
  video: ArchivalFile | null;
  audio: ArchivalFile | null;
  link: string | null;
  tag: PostTagObject[];
}

// Child objects are read from their parent's file, so they have no path/order.
export interface PostTagObject {
  name: string | null;
}

/** Every object in the site, keyed by name. */
export interface ArchivalObjects {
  site: SiteObject;
  post: PostObject[];
}

declare module "@archival/carrier" {
  interface SiteObjects extends ArchivalObjects {}
}
