number = 4
title = "Something Interesting"
description = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio. 
Join us as we explore some truly fascinating topics that caught our attention this week.
"""
duration = "41:22"
publish_date = "2024-12-20"
featured = false
draft = false
tag1 = "music"
tag2 = "news"
host1 = "host-1"
host2 = "host-2"
order = 4

[audio_url]
uploaded = 9
sha = "ddc7cec156c15a22718064968c13b0ca7c7bf245efbff9fb833c208753c77904"
filename = "band-track-01.mp3"
mime = "audio/mpeg"
display_type = "audio"

[thumbnail]
sha = "98d2abe69a4053618becb1ef5ef06617a8106f5fd1980901196f81087b40d77f"
filename = "13.jpg"
mime = "image/jpeg"
display_type = "image"
