order = 1
group = "Some Features"
brief = "Getting started"
title = "Here is the feature name"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at ipsum eu nunc commodo posuere et sit amet ligula."
button_title = "Action"
button_link = "#"
