name: Archival
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Archival Build
        uses: jesseditson/archival@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
